### ISSUE TITLE
Dynamic Get (snippet) not work in custom admin view

### ISSUE THREAD

**Issue by sepehr09** [vdm-io/Joomla-Component-Builder#155]
hi.in custom admin view the Dynamic Get (snippet) not working & show nothing !

![image](https://user-images.githubusercontent.com/11753906/32172469-f6657bdc-bd90-11e7-8a0a-fa08f1673fa6.png)

![image](https://user-images.githubusercontent.com/11753906/32172504-175527fc-bd91-11e7-8786-e1305146ab72.png)

![image](https://user-images.githubusercontent.com/11753906/32172557-476024d8-bd91-11e7-8b73-7748454a5e20.png)

thanks

**Comment by Llewellynvdm** [comment]
IT has been fixed in the v2.6.0 that is nearly finished.

**Comment by sepehr09** [comment]
thank you very much
also i have problem in dynamics get i guess if alias isn't set in admin view this will happend :
![image](https://user-images.githubusercontent.com/11753906/32172720-ce664b4c-bd91-11e7-87e2-f77d6c5ea74e.png)

**Comment by Llewellynvdm** [comment]
Also fixed in the next release.

**Comment by sepehr09** [comment]
i updated to version 2.7 but still not fixed (both): 
![image](https://user-images.githubusercontent.com/11753906/32224828-4145d918-be58-11e7-93d4-ffcf063a0d46.png)

![image](https://user-images.githubusercontent.com/11753906/32224892-699ffca4-be58-11e7-90b5-142c3f8cd31b.png)

i also clear browser cache!

**Comment by Llewellynvdm** [comment]
Does it work with other views? I mean I see it does not want to work with __privatemassages__ does it work with other?

> Also the Custom Admin View will not return any values if the dynamic get has none set.

In the dynamicGet I see "undefined index alias..." on line 1113 please open that file and replace with these lines:
```
// insure it is set to alias if needed
if (isset($value['alias']) && $value['alias'] == 1)
{
	$field[$nr]['name'] = 'alias';
}
```
This should resolve that issue, it is a new bug that is caused by the checkbox behavior in the subforms. Real headache, since in the subform if the checkbox is not ticked, it drops the whole thing and does not even load it into the array stored in the database (so the undefined index nightmare). I can see many issues are related to this at this point. So you will see the last few commits are already fixing these.

Sorry about that...

**Comment by Llewellynvdm** [comment]
Sorry there seems to be one more line to change in the [ajax.php](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/models/ajax.php) model. On line [1321](https://github.com/vdm-io/Joomla-Component-Builder/blob/master/admin/models/ajax.php#L1321) replace it with:
```
if ('template' === $view || 'site_view' === $view || 'custom_admin_view' === $view)
```
This should resolve the issue at last.
