### ISSUE TITLE
Issue with JCB 2.7.2

### ISSUE THREAD

**Issue by peterpetrov** [vdm-io/Joomla-Component-Builder#262]
### System information
Centos 7.2
PPH-FPM 7.2
Nginx 1.12.2
DB MariaDB 10.0.34
Joomla 3.8.6

### Steps to reproduce the issue
1. Install JCB 2.7.2 (clean or on top of older version or update - does not make a difference)
2. Go to Fields - New
3. Select a field type from the drop down 
4. The issue - Field properties does not appear. 

### Expected result

Field properties to appear

### Actual result

1. Fields does not appear
2. 500 server error Ajax error in console
3. PHP error:

PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /web/website.com/administrator/components/com_componentbuilder/tables/component_updates.php on line 268" while reading response header from upstream, client: 91.139.200.112, server: website.com, request: "POST /administrator/index.php?option=com_componentbuilder&view=compiler HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "website.com", referrer: "https://website.com/administrator/index.php?option=com_componentbuilder&view=compiler"
2018/04/13 02:51:49 [error] 22224#0: *1172 FastCGI sent in stderr: "PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /web/website.com/administrator/components/com_componentbuilder/views/library/tmpl/edit.php on line 282" while reading response header from upstream, client: 91.139.200.112, server: website.com, request: "GET /administrator/index.php?option=com_componentbuilder&view=library&layout=edit&id=3 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "website.com", referrer: "https://website.com/administrator/index.php?option=com_componentbuilder&view=libraries"

### Additional comments

It works properly on the JCB 2.7.1 version.

**Comment by Llewellynvdm** [comment]
This as many times before is extremely weird... but okay I have made the needed fixes on the account of those errors, thanks!

It will be patched in the next update.

**Comment by bosyrih** [comment]
the same thing for custom field the type-php disrepair after save the field.

**Comment by Llewellynvdm** [comment]
Well please try the latest update, as it has been fixed as much as I could. All our test are working and I see none of those errors.

**Comment by bosyrih** [comment]
I'd update from 2.7.2 to 2.7.3 and try it again,
the problem still in v2.7.3 my version of joomla is 3.8.5 there is no error message .
 the problem is :
if i add field and set it as custom type  for list and put all properties and save it,
if i open the field again all properties for php-type_1 to 19  are gone.

**Comment by Llewellynvdm** [comment]
Okay I see it... and I am on it!

**Comment by Llewellynvdm** [comment]
I found the issue.. and is due to me trying to do things more secure.

On line [907](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/field.php#L907) I am making the name safe and this is breaking the php placeholders since it has numbers, removing that line will fix the issue.

**Comment by bosyrih** [comment]
ok thanks ,
It seem not like peterpetrov issue, or Is it same issue.
if it not the same issue can we take it to new one .

**Comment by Llewellynvdm** [comment]
Well @peterpetrov issue has also been resolved, in last update. What you pointed out was also related to the same area, but yes not exactly the same. But no worries, both should now be fixed.
