### ISSUE TITLE
Edit/Create Site View Edit Button code "Broken"

### ISSUE THREAD

**Issue by mwweb** [vdm-io/Joomla-Component-Builder#335]
### Steps to reproduce the issue
Compile and install Demo component. Add a Look. Edit permissions (I set user group "Registered" Edit, Edit Own, Looks Edit, and Looks Edit Own to Allowed). Add Demo to menu, go to site view, and log in as a user that is part of the Registered group, then go to Demo. The edit link shows, but if you click the button you get "Error Edit not permitted."

If you add `var_dump($canDo);exit;` in the looks.php model just below the $canDo, then reload the page, you can see that the permissions look correct, but you are unable to edit.

### Expected result
When clicking on the edit button, I should be directed to the edit view, as long as my user group is AT LEAST Registered, and there is a record which I created.

### Actual result
The edit button only works for Super Admin. No other user group ACL works.

### System information (as much as possible)
- OS Name & Version: 14.04.1-Ubuntu
- MySql Version: 5.5.5-10.1.28-MariaDB-1~trusty
- Apache Version: 2.4.29
- PHP Version: HP Version 7.1.18-1
- Joomla Version: 3.8.11
- JCB Version: 2.9.0
- Browser: Chrome

### Additional comments
This has been tested with JCB 2.8.5 as well.

**Comment by Llewellynvdm** [comment]
There is an access switch, that block all access to the view, that also must be set to allowed. It may have been fixed in some of the last updates, and only started working now. But it has been around from the start.

Here is how I have the permissions set, and then it works:
![image](https://user-images.githubusercontent.com/5607939/44996664-6c883600-afa9-11e8-84de-20fce0428dd2.png)

**Comment by mwweb** [comment]
That didn't fix it, so I've tabled it for the time being as I've been working on a major change to my component, due to performance issues.

**Comment by Llewellynvdm** [comment]
Why open the issue if you are not willing to work with me to resolve it.

JCB does not get the same problem to me, so I can't debug or even know what is wrong unless you give me feedback. The only change that may have effected this area is the extra permissions, that was added surrounding fields, but the demo component has none of those turned on. So with the above settings I am able to login as a registered user and edit exiting values. This is the same in the [bitnamimi environment](https://www.youtube.com/watch?v=zpS52k89YcI&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=73&t=0s), so unless you explain more to me, I can fix this.

**Comment by mwweb** [comment]
OK. I got some time to dig more into this. My big project encountered a major issue, that resulted in my having to code several AJAX functions.

Anyway, if you look at the following video capture, you will see that I have 2 records in Looks in the demo component. One record is created by Super User, the other created by User. Permissions look set.

Now, when I go into the looking site view, the edit button is showing for BOTH records, even though USER only owns one record. As user, I can edit BOTH records, even though I don't have ownership of the second one.

[https://dev.mwweb.host/temp/demo_user-permissions.webm](url)

**Comment by mwweb** [comment]
The problem is, I forgot to add to what I said above, but I did test by turning OFF Looks Edit, leaving only Looks Edit Own, and the result is that no buttons show. They will only show, when edit own is on, if user is Super Admin, even though the permission is set as allowed in Registered:

Permissions:
![looks-permissions](https://user-images.githubusercontent.com/19194012/45458545-00908680-b6a9-11e8-8639-48d39d32d3c2.png)

Site View with Looks Edit Not Allowed, but Looks Edit Own as Allowed:
![looks_site](https://user-images.githubusercontent.com/19194012/45458580-24ec6300-b6a9-11e8-9489-4b1c5c0a2856.png)

**Comment by Llewellynvdm** [comment]
Sorry about that, it is a small error really, we must add the **created_by** to the dynamicGet, since it is required to validate the ownership. So a quick fix to just demonstrate it, add the following to [line 68 of the model](https://github.com/namibia/demo-joomla-3-component/blob/master/site/models/looks.php#L68).
```
$query->select($db->quoteName(array('a.created_by')));
```
To fix this via JCB open the dynamic get and add the following to the `a.created_by AS created_by` to the selection text area of the looks (getListQuery) and compile and install and all should work as expected.

I will update the package to ship with this little fix :+1:

**Comment by Llewellynvdm** [comment]
Okay I have updated the demo package even in the community packages, so you could just import the demo JCB package and compile and this will also fix this issue.

**Comment by mwweb** [comment]
So, in short, it was due to created_by not being  part of the get

**Comment by Llewellynvdm** [comment]
Yes, that was it... shocking to think you are the first to pick this up, thanks!

**Comment by Llewellynvdm** [comment]
Here is some script I use in my helper class to also build edit button, using a little pencil icon from UIKIT.
```
/**
* Get an edit button
* 
* @param  int      $item       The item to edit
* @param  string   $view       The type of item to edit
* @param  string   $views      The list view controller name
* @param  string   $ref        The return path
* @param  string   $component  The component these views belong to
* @param  string   $headsup    The message to show on click of button
*
* @return  string    On success the full html edit button
* 
*/
public static function getEditButton(&$item, $view, $views, $ref = '', $component = 'com_[[[component]]]', $headsup = JustTEXT::_('All unsaved work on this page will be lost, are you sure you want to continue?'))
{
	// get URL
	$url = self::getEditURL($item, $view, $views, $ref, $component);
	// check if we found any
	if (self::checkString($url))
	{
		// check that we have the ID
		if (self::checkObject($item) && isset($item->id))
		{
			// check if the checked_out is available
			if (isset($item->checked_out))
			{
				$checked_out = (int) $item->checked_out;
			}
		}
		elseif (self::checkArray($item) && isset($item['id']))
		{
			// check if the checked_out is available
			if (isset($item['checked_out']))
			{
				$checked_out = (int) $item['checked_out'];
			}
		}
		// set the link title
		$title = self::safeString(JText::_('Edit') . ' ' . $view, 'W');
		// check that there is a check message
		if (self::checkString($headsup))
		{
			$href = 'onclick="UIkit2.modal.confirm(\''.JText::_($headsup).'\', function(){ window.location.href = \'' . $url . '\' })"  href="javascript:void(0)"';
		}
		else
		{
			$href = 'href="' . $url . '"';
		}
		// check if it is checked out
		if (isset($checked_out) && $checked_out > 0)
		{
			// is this user the one who checked it out
			if ($checked_out == JFactory::getUser()->id)
			{
				return ' <a ' . $href . ' class="uk-icon-lock" title="' . $title . '"></a>';
			}
			return ' <a href="#" disabled class="uk-icon-lock" title="' . JText::sprintf('% has been checked out by %s', self::safeString($view, 'W'), JFactory::getUser($checked_out)->name) . '"></a>'; 
		}
		// return normal edit link
		return ' <a ' . $href . ' class="uk-icon-pencil" title="' . $title . '"></a>';
	}
	return '';
}

/**
* Get the edit URL
* 
* @param  int      $item        The item to edit
* @param  string   $view        The type of item to edit
* @param  string   $views       The list view controller name
* @param  string   $ref         The return path
* @param  string   $component   The component these views belong to
* @param  bool     $jRoute      The switch to add use JRoute or not
*
* @return  string    On success the edit url
* 
*/
public static function  getEditURL(&$item, $view, $views, $ref = '', $component = 'com_[[[component]]]', $jRoute = true)
{
	// check that we have the ID
	if (self::checkObject($item) && isset($item->id))
	{
		$id = (int) $item->id;
		// check if created_by is available
		if (isset($item->created_by) && $item->created_by > 0)
		{
			$created_by = (int) $item->created_by;
		}
	}
	elseif (self::checkArray($item) && isset($item['id']))
	{
		$id = (int) $item['id'];
		// check if created_by is available
		if (isset($item['created_by']) && $item['created_by'] > 0)
		{
			$created_by = (int) $item['created_by'];
		}
	}
	elseif (is_numeric($item))
	{
		$id = (int) $item;
	}
	// check ID
	if (isset($id) && $id > 0)
	{
		// get user object
		$user = JFactory::getUser();
		// can edit
		if ($user->authorise($view . '.edit', $component . '.' . $view . '.' . (int) $id) ||
			(
				isset($created_by) && $created_by == $user->id &&
				(
					$user->authorise($view . '.edit.own', $component . '.' . $view . '.' . (int) $id) ||
					$user->authorise('core.edit.own', $component . '.' . $view . '.' . (int) $id) ||
					$user->authorise('core.edit.own', $component)
				)
			)
		)
		{
			// set the edit link
			if ($jRoute)
			{
				return JRoute::_("index.php?option=" . $component . "&view=" . $views . "&task=" . $view . ".edit&id=" . $id . $ref);
			}
			return "index.php?option=" . $component . "&view=" . $views . "&task=" . $view . ".edit&id=" . $id . $ref;
		}
	}
	return false;
}

```
It has an automatic pop-up notice that can be set per button, and it also deals with return value, to bring the user back the the original point where they started the click path. I have added it the JCB and it is what is now used to handle most of the edit buttons all around. It also deals with the **edit own** concept.

**Comment by Llewellynvdm** [comment]
I have upgraded the [getActions helper method](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/componentbuilder.php#L4573), and pushed it to the JCB staging branch, it should work better now, since it will get the created_by value, in-case it is not part of the item. Please have a look, and run some test when you have time. Thanks!
