### ISSUE TITLE
Cant' save JCB configuration in current staging

### ISSUE THREAD

**Issue by marcodings** [vdm-io/Joomla-Component-Builder#424]
### Steps to reproduce the issue
staging 12 june,
open jcb configuration and hit save button

### Expected result
save without problems

### Actual result
error is thrown
![image](https://user-images.githubusercontent.com/3484222/59419132-8cffdf00-8dca-11e9-922c-c50a85efda57.png)

### Additional comments
Probably due to the results of handling of required fields in subform ?

**Comment by peterpetrov** [comment]
Hey Marco, that has been fixed at the latest staging build. Please update and try again.

Also the staging build is still beta version so issues are expected.

Regards,
Peter

**Comment by marcodings** [comment]
@peterpetrov did you assume or did you try? As the problem persists in the most recent staging?

And yes i'm very much aware of what beta means, i'm reporting problems, not complaining

**Comment by Llewellynvdm** [comment]
Okay I see this is an issue in the global settings of JCB, I did not go over that area... and yes it is related to the subform permissions now working :man_facepalming:

I did fix it all over the component exept in the global settings, thanks :+1: will push the fix out soon.
